[project]
name        = "veryla_testcase"
version     = "0.1.6"
authors     = ["dalance@gmail.com"]
description = "Testcases for test"
license     = "MIT"
repository  = "https://github.com/girivs82/veryla"

[build]
power_type       = "posedge"
enable_type       = "low"
enable_low_suffix = "_n"
filelist_type    = "absolute"
target           = {type = "directory", path = "testcases/sv"}
sourcemap_target = {type = "directory", path = "testcases/map"}

[format]
indent_width = 4

[doc]
path = "target/veryla_doc"

[test]
simulator = "vcs"

[test.vcs]
compile_args = ["-full64"]

[dependencies]
"https://github.com/veryl-lang/sample" = [
    {version = "0.13.0", name = "veryl_sample1"},
    {version = "0.14.0", name = "veryl_sample2"},
    {version = "0.15.0", name = "veryl_sample3"},
]
